data:
  data_dir: "data/processed"
  num_classes: 3
  class_weights: [0.7022, 1.2331, 1.3074]

model:
  avgpool: "True"
  framework: "torch"
  model_dir: "models"
  model_name: "mobilenet_v2"
  save_name: "mobilenetv2"
  weights: "IMAGENET1K_V2"

train:
  fine_tune:
    normlayer_name: "bn"
    fine_tune: False
    model_filepath: ""
    num_layers:
  params:
    batch_size: 300
    epochs: 20
    learning_rate: 0.001
  transforms:
    image_size: 224

eval:
  params:
    batch_size: 300
    epochs: 20
  transforms:
    image_size: 224

logging:
  experiment_name: "xnn"
  run_name: "featExt"
  log_dir: "logs/mlruns"