data:
  data_dir: "data/processed"
  num_classes: 3
  class_weights:
  # class_weights: [0.7022, 1.2331, 1.3074]

model:
  avgpool: "False"
  framework: "torch"
  model_dir: "models"
  model_name: "resnet50"
  save_name: "resnet_ft"
  weights: "IMAGENET1K_V2"

train:
  fine_tune:
    normlayer_name: "bn"
    fine_tune: True
    model_filepath: ""
    num_layers: 10
  metrics:
    average: "weighted"
  params:
    batch_size: 100
    epochs: 20
    learning_rate: 0.00001
  transforms:
    image_size: 224

eval:
  params:
    batch_size: 100
  transforms:
    image_size: 224

logging:
  experiment_name: "xnn"
  run_name: "fineTune"
  log_dir: "logs/mlruns"