data:
  data_dir: "data/processed"
  num_classes: 3

model:
  framework: "torch"
  model_dir: "models"
  model_filepath: ""
  model_name: "resnet50"
  save_name: "resnet"

train:
  fine_tune: False
  params:
    batch_size: 300
    epochs: 2
    learning_rate: 0.001
  transforms:
    image_size: 224

eval:
  params:
    batch_size: 300
    epochs: 30
  transforms:
    image_size: 224

logging:
  experiment_name: "xnn"
  run_name: "featExt"
  log_dir: "logs/mlruns"